Add dynamic run index <<>> option
Donders-Institute/bidscoin pull request #195
Opened 2023-08-09 20:00 UTC by DominikaZ

## Feature request: dynamic run index naming

Hello,

I would like to suggest a small extension to the way how dynamic run indexes are handled. Right now, with option run `<<1>>`, each filename will get `run` keyval, even when it doesn’t need it when no more runs are present. It would be amazing if there was an option to automatically increment run index while not to include it in the filename if it is not needed, as that pollutes a bit the filenames.

I suggest a solution which preserves the original behavior for dynamic `<<1>>` run index, but for `<<>>` empty run index files are named without `run` keyval. Only when file with the same name is found, bidscoin adds `run-2` index to its filename and retrospectively adds `run-1` to the corresponding other file with which it has matched. Next found run gets `run-3`, `run-4` etc.

What do you think about the solution?
I might have missed some errors this could introduce, although I tested the results.

As an alternative approach, I've been thinking about making a script that would run after bidscoin, renaming the files. But that would also mean all references to the files would need to be renamed.

2023-08-14 08:32 UTC, marcelzwiers commented
Hi, thanks for your suggestion. I considered this in the past but, without making things much more complicated, I figured you may end up with folders such as:
```console
bids/sub-001/func/                                                                                                                            
|-- sub-001_task-rest_bold.json                                                                                         
|-- sub-001_task-rest.nii.gz                                                                                       
|-- sub-001_task-rest_run-2_bold.json                                                                                       
`-- sub-001_task-rest_run-2_bold.nii.gz                                                                                     
```
I figured that may be very confusing for bids apps, when they encounter a `run-2` image, but cannot find a `run-1` image (you'd have to rename the run-less image into a run-1 image). I'm not even sure if that is BIDS compliant (haven't tested it with bids-validator). I therefore decided it was better to be always explicit about the run-index, unless you are sure there is always only 1 run (in which case you can just delete `<<1>>` run-index to have it removed from the filename)

2023-08-14 15:20 UTC, marcelzwiers requested changes

2023-08-14 15:20 UTC, marcelzwiers commented on bidscoin/bids.py
> +def remove_run_keyval(bidsname: str) -> str:
I think this function is not needed and can be achieved by calling `insert_keyval(bidsname, 'run', '', False)`

2023-08-15 08:32 UTC, marcelzwiers commented
If you have some subjects with one run and others with multiple runs, you do get inconsistent naming of the first run when using `<<>>`. It can be desirable, just saying:
 
```
bids/sub-001/func/                                                                                                                            
   |-- sub-001_task-rest_bold.json                                                                                       
   `-- sub-001_task-rest_bold.nii.gz                                                                                     
bids/sub-002/func/                                                                                                                            
   |-- sub-002_task-rest_run-1_bold.json                                                                                       
   |-- sub-002_task-rest_run-1_bold.nii.gz                                                                                       
   |-- sub-002_task-rest_run-2_bold.json                                                                                       
   `-- sub-002_task-rest_run-2_bold.nii.gz                                                                                     
```

2023-08-17 10:55 UTC, marcelzwiers commented
Your solution looks good to me, I might even make the new `<<>>` run-index the default. Would you happen to have time to implement my suggestions?

2023-08-18 06:02 UTC, merged

2023-08-18 06:02 UTC, marcelzwiers commented
Perfect, thanks a lot! I like the new `<<>>` option more than I expected and will make it the new default :-)

2023-08-18 12:38 UTC, marcelzwiers commented
I refactored (3c9b8963ff64173601f9fb6dc5e84a8e9bdafaf8) your PR a bit, i.e. I moved code that is central to bidscoin out of the plugins. But now I messed up the tests a bit... I'm not really familiar with unittest mocking, and I'm struggling to get it all right. It would be really nice if you can fix your tests and help me out :-)

2023-08-21 16:33 UTC, marcelzwiers commented
Ok, I rewrote your mock tests because I think that mocking system libraries is fragile and a bad idea

2023-08-21 18:01 UTC, DominikaZ commented
> Ok, I rewrote your mock tests because I think that mocking system libraries is fragile and a bad idea

Hello, sorry for replying so late.
I have time tomorrow evening to rewrite the tests but if you are content with the ones you wrote that is fine by me :).

Mocking is good for test isolation, when a test fails we know that this concrete tested function failed and not other external factor e.g function that it used. Furthermore, one doesn't need to actually create the resources.

I can see that you want to avoid adding new dependency and also want to use code that you fully understand, so it is easier to maintain.

2023-08-21 21:09 UTC, marcelzwiers commented
You don't need to rewrite your tests, but if you like you can review the new tests to see if it misses anything (you'll see I need less and easier code to generate some temporary files than you did to mock `pathlib.glob()`).

I think mocking can be suitable for testing code in cases where you don't have control over certain functions (such as functions that read out sensors in an industrial process, or functions that communicate with web servers). Otherwise, I think you should stay away from mocking if you can -- especially from mocking common system libraries. The reason is that mocking is very fragile: you are mocking the functions in the code you like to test, but in fact, mocking can have side effects outside the scope of the code you like to test. For instance, if your mocking works today, it may be broken tomorrow if a dependency of the functions you test gets updated and starts also using the function that you mocked. For instance, you are mocking `pathlib` and then one of your dependencies switches from using `os.path` to `pathlib`.  Perfectly fine and logical update, except that your test now fails (while it shouldn't).

2023-08-22 18:58 UTC, DominikaZ commented
Yeah, you are right that my tests were a bit tightly coupled to the implementation and the new tests look much cleaner and cover everything needed :).

2023-08-22 19:37 UTC, marcelzwiers commented
Thanks again for your contribution, I like it so much that I made it the new default :-)

2023-08-26 15:08 UTC, DominikaZ commented
I am happy I could contribute a bit :).